# Generated by Django 5.1 on 2024-09-04 17:55

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image0', models.ImageField(upload_to=main.models.Product.get_path_file)),
                ('image1', models.ImageField(upload_to=main.models.Product.get_path_file)),
                ('image2', models.ImageField(upload_to=main.models.Product.get_path_file)),
                ('image3', models.ImageField(upload_to=main.models.Product.get_path_file)),
                ('image4', models.ImageField(upload_to=main.models.Product.get_path_file)),
                ('image5', models.ImageField(upload_to=main.models.Product.get_path_file)),
                ('gender', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productcategorys')),
            ],
        ),
    ]
