# Generated by Django 5.1 on 2024-09-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ProductCategorys',
            new_name='ProductCategory',
        ),
    ]
