# Generated by Django 5.1 on 2024-09-07 12:40

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_products_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image0',
            field=models.ImageField(null=True, upload_to=main.models.Product.get_path_file),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(null=True, upload_to=main.models.Product.get_path_file),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(null=True, upload_to=main.models.Product.get_path_file),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(null=True, upload_to=main.models.Product.get_path_file),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(null=True, upload_to=main.models.Product.get_path_file),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(null=True, upload_to=main.models.Product.get_path_file),
        ),
    ]
